# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbfc7e1400ce9dc4411e31abe68af84b291e810159e310e21be15466544f4f55f32f720d9b97343072628b3bb2379c5fa4c040aa2a1dcb433f669577d1b8fa27

test:
  secret_key_base: 8ab0a5cd1e98a02e7e3de3f1f6e8ada2de6c5ff5ea495978e5ee87db3b05635710cd290b1083e8900b297ca5f0a8e82d736256faa4535c98e91fb6bf52818e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
